# === AI GENERATED FUNCTION (Claude) - 2025-06-29 ===
# Test the new ADSH-based extraction function
from data_loaders.sec_api_loaders.fetch_and_parse_submission_for_financial_concept_by_cik_and_adsh import (
    fetch_and_parse_submission_for_financial_concept_by_cik_and_adsh,
)


def perform_adsh_extraction():
    """
    AI Generated Function: Test ADSH-based extraction functionality
    Generated by Claude on 2025-06-29 to test the fetch_and_parse_submission_by_adsh function

    Test the fetch_and_parse_submission_by_adsh function using a known ADSH.
    This function extracts all instances of a concept from a specific filing.
    """

    print("TESTING ADSH-BASED CONCEPT EXTRACTION")
    print("=" * 60)

    # Test case: FDX Q1 2025 filing from the missing filings report
    cik = "1048911"  # FDX
    adsh = "0000950170-24-108107"  # From the missing filings report
    concept_tag = "RevenueFromContractWithCustomerExcludingAssessedTax"  # Try a common revenue concept

    print(f"Testing extraction from ADSH: {adsh}")
    print(f"CIK: {cik}")
    print(f"Concept: {concept_tag}")
    print("-" * 40)

    try:
        result = fetch_and_parse_submission_for_financial_concept_by_cik_and_adsh(
            cik=cik, adsh=adsh, fact_tag=concept_tag
        )

        if result.get("error"):
            print(f"Error: {result['error']}")
            print(f"Document URL attempted: {result.get('document_url', 'N/A')}")
        else:
            print(f"Document URL: {result['document_url']}")
            print(
                f"Found {len(result.get('all_facts', []))} total facts for '{concept_tag}'"
            )

            # Show all facts found
            for i, fact in enumerate(result.get("all_facts", []), 1):
                print(f"\nFact {i}:")
                print(f"  Value: {fact.get('value', 'N/A')}")
                print(f"  Numeric Value: {fact.get('numeric_value', 'N/A')}")
                print(f"  Actual Value: {fact.get('actual_value', 'N/A')}")
                print(f"  Unit: {fact.get('unit_ref', 'N/A')}")
                print(f"  Context: {fact.get('context_ref', 'N/A')}")
                print(f"  Period Start: {fact.get('period_start', 'N/A')}")
                print(f"  Period End: {fact.get('period_end', 'N/A')}")
                print(f"  Period Type: {fact.get('period_type', 'N/A')}")
                print(f"  Decimals: {fact.get('decimals', 'N/A')}")
                print(f"  Extraction Method: {fact.get('extraction_method', 'N/A')}")

            # Show the best fact
            best_fact = result.get("best_fact")
            if best_fact:
                print(f"\nBEST FACT (Most Recent):")
                print(
                    f"  Value: {best_fact.get('actual_value', best_fact.get('numeric_value', best_fact.get('value', 'N/A')))}"
                )
                print(f"  Unit: {best_fact.get('unit_ref', 'N/A')}")
                print(
                    f"  Period: {best_fact.get('period_start', 'N/A')} to {best_fact.get('period_end', 'N/A')}"
                )
                print(f"  Context: {best_fact.get('context_ref', 'N/A')}")

    except Exception as e:
        print(f"Error during test: {e}")
        import traceback

        print(traceback.format_exc())

    print("\n" + "=" * 60)


# === AI GENERATED FUNCTION END ===
