import os
from data_loaders.sec_api_loaders.fetch_and_parse_submission_enhanced_by_cik_and_adsh import (
    fetch_and_parse_submission_enhanced_by_cik_and_adsh,
)
from scrape_processing_scripts.scrape_process_tradingview_webpages import (
    extract_companies_from_tradingview_screener_html,
)
from data_analysis_scripts.analisys_by_industry import (
    process_revenues_for_tickers,
)


# === Simple utility to add 'processed' field to all_cik_ticker_pairs_with_financial_concepts_data_v2.json ===
def add_processed_field_to_cik_ticker_json(json_path=None):
    """
    Adds a 'processed' field (0) to each entry in the JSON file for tracking.
    """
    if json_path is None:
        project_root = os.path.dirname(os.path.dirname(__file__))
        json_path = os.path.join(
            project_root,
            "savedData",
            "all_cik_ticker_pairs_with_financial_concepts_data_v2.json",
        )
    import json

    with open(json_path, "r", encoding="utf-8") as f:
        data = json.load(f)
    changed = False
    for entry in data:
        entry["processed"] = 0
        changed = True
    if changed:
        with open(json_path, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=2)
        print(f"Updated {json_path} with 'processed' field.")
    else:
        print(f"No changes needed, all entries already have 'processed' field.")


# === AI GENERATED FUNCTION (Claude) - 2025-06-29 ===
# Demonstrate the enhanced period validation functionality.
def test_enhanced_period_validation():
    """
    AI Generated Function: Test enhanced period validation functionality
    Generated by Claude on 2025-06-29 to demonstrate period extraction improvements

    This function shows how the new extraction method validates that extracted
    concepts correspond to the correct reporting period.
    """

    print("TESTING ENHANCED PERIOD VALIDATION")
    print("=" * 60)

    # Test cases with different companies and periods
    test_cases = [
        {
            "company": "FDX (FedEx)",
            "cik": "1048911",
            "form": "10-Q",
            "period": "Q1",
            "year": 2024,
            "expected_date": "2024-08-31",  # Expected quarter end for FDX Q1 FY2024
            "concept": "RevenueFromContractWithCustomerExcludingAssessedTax",
        },
        {
            "company": "MU (Micron)",
            "cik": "723125",
            "form": "10-Q",
            "period": "Q1",
            "year": 2025,
            "expected_date": "2024-11-28",  # Expected quarter end for MU Q1 FY2025
            "concept": "RevenueFromContractWithCustomerExcludingAssessedTax",
        },
    ]

    for i, test_case in enumerate(test_cases, 1):
        print(f"\nTest Case {i}: {test_case['company']}")
        print(f"Extracting {test_case['concept']}")
        print(f"From {test_case['form']} {test_case['period']} {test_case['year']}")
        print(f"Expected period end: {test_case['expected_date']}")
        print("-" * 40)

        try:
            result = fetch_and_parse_submission_enhanced_by_cik_and_adsh(
                test_case["cik"],
                test_case["form"],
                test_case["period"],
                test_case["year"],
                test_case["concept"],
                test_case["expected_date"],
            )

            if result.get("fact_value"):
                period_status = (
                    "VALIDATED" if result.get("period_validation") else "NOT VALIDATED"
                )
                print(f"Value found: {result['fact_value']} {result.get('fact_unit')}")
                print(f"Context: {result.get('fact_context')}")
                print(f"Period start: {result.get('fact_period_start', 'N/A')}")
                print(f"Period end: {result.get('fact_period_end', 'N/A')}")
                print(f"Period validation: {period_status}")
                print(
                    f"All contexts found: {len(result.get('all_contexts_found', []))} contexts"
                )

                if result.get("fact_decimals"):
                    try:
                        value = float(result["fact_value"])
                        decimals = int(result["fact_decimals"])
                        actual_value = (
                            value * (10 ** abs(decimals)) if decimals < 0 else value
                        )
                        print(
                            f"Calculated actual value: {actual_value:,.0f} {result.get('fact_unit')}"
                        )
                    except Exception as e:
                        print(f"Could not calculate actual value: {e}")
            else:
                print(f"Error: {result.get('error', 'No value found')}")
                print(
                    f"Contexts found: {len(result.get('all_contexts_found', []))} contexts"
                )

        except Exception as e:
            print(f"Exception during extraction: {e}")
            import traceback

            print(traceback.format_exc())

    print("\n" + "=" * 60)
    print("INTERPRETATION:")
    print("VALIDATED = The extracted value corresponds to the correct reporting period")
    print(
        "NOT VALIDATED = The value may be from a different period (compare periods shown)"
    )
    print("ERROR = Could not extract the concept from the filing")


# === AI GENERATED FUNCTION END ===


# Main entry point for running workflows and data loaders.
def main():
    base_data_dir = r"D:\FinanceProjects\edgarFinancialStatements"

    tickers = []

    for el in extract_companies_from_tradingview_screener_html():
        ticker = el.get("ticker")
        if ticker:
            tickers.append(ticker)

    process_revenues_for_tickers(tickers, start_year=2015)

    pass


if __name__ == "__main__":
    main()
